# We use the latest Rust stable release as base image
FROM rust:latest AS builder
# Let's switch our working directory to `app` (equivalent to `cd app`)
# The `app` folder will be created for us by Docker in case it does not
# exist already.
WORKDIR /app
# Install the required system dependencies for our linking configuration
RUN apt update && apt install lld clang -y
# Copy all files from our working environment to our Docker image
COPY . .

# Set the SQLX_OFFLINE environment variable to true for sqlx to work offline
ENV SQLX_OFFLINE=true

# Let's build our binary!
# We'll use the release profile to make it faaaast
RUN cargo build --release

# TODO:Runtime stage (OPTION 1)
# FROM rust:slim AS runtime

# WORKDIR /app

# COPY --from=builder /app/target/release/zero2prod zero2prod

# # CONFIGURATION FILES ARE REQUIRED FOR THE RUNTIME STAGE
# # Copy the configuration files from the build context for the runtime stage
# COPY configuration configuration

# # Set the APP_ENVIRONMENT environment variable to production - the other option is local which is the default and is used for development
# ENV APP_ENVIRONMENT=production


# # When `docker run` is executed, launch the binary!
# ENTRYPOINT ["./zero2prod"]


# TODO: Faster, slimmer build (OPTION 2)
FROM debian:bookworm-slim AS runtime
WORKDIR /app
# Install OpenSSL - it is dynamically linked by some of our dependencies
# Install ca-certificates - it is needed to verify TLS certificates
# when establishing HTTPS connections
RUN apt-get update -y \
&& apt-get install -y --no-install-recommends openssl ca-certificates \
# Clean up
&& apt-get autoremove -y \
&& apt-get clean -y \
&& rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/zero2prod zero2prod
COPY configuration configuration
ENV APP_ENVIRONMENT=production
ENTRYPOINT ["./zero2prod"]